[package]
name = "seventeenth"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.0.29", features = ["derive"] }
enum-iterator = "1.2.0"
euclid = "0.22.7"
itertools = "0.10.5"
num-derive = "0.3.3"
num-traits = "0.2.15"
