[package]
name = "fifteenth"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.29", features = ["derive"] }
euclid = "0.22.7"
itertools = "0.10.5"
regex = "1.7.0"
