[package]
name = "fourteenth"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.29", features = ["derive"] }
euclid = "0.22.7"
itertools = "0.10.5"
ndarray = "0.15.6"
nom = "7.1.1"
